[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/cryptlink-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
JAVA_VERSION = "17"
NODE_VERSION = "18"
